BEGIN TRANSACTION;
DROP TABLE IF EXISTS `UserInfo`;
CREATE TABLE IF NOT EXISTS `UserInfo` (
	`UserNo`	INTEGER NOT NULL,
	`UserType`	INTEGER NOT NULL,
	PRIMARY KEY(`UserNo`)
);
DROP TABLE IF EXISTS `CourseSelection`;
CREATE TABLE IF NOT EXISTS `CourseSelection` (
	`UserNo`	INTEGER NOT NULL,
	`CourseNo`	INTEGER NOT NULL,
	`SchoolYear`	INTEGER NOT NULL,
	`Semester`	INTEGER NOT NULL
);
COMMIT;
