BEGIN TRANSACTION;
DROP TABLE IF EXISTS `UserInfo`;
CREATE TABLE IF NOT EXISTS `UserInfo` (
	`UserNo`	INTEGER NOT NULL,
	`UserType`	INTEGER NOT NULL,
	PRIMARY KEY(`UserNo`)
);
INSERT INTO `UserInfo` VALUES (1,0);
COMMIT;
