BEGIN TRANSACTION;
DROP TABLE IF EXISTS `UserProfile`;
CREATE TABLE IF NOT EXISTS `UserProfile` (
	`UserNo`	INTEGER NOT NULL DEFAULT 106000000 PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserName`	TEXT NOT NULL,
	`UserID`	TEXT NOT NULL UNIQUE,
	`UserPW`	TEXT NOT NULL,
	`Authorization`	TEXT NOT NULL
);
INSERT INTO `UserProfile` VALUES (1,'王小明','0001','oHXRfz1FMHOFP4E4OMFbgCO4xIcDhDY1T+WZw5QuH5U=','');
COMMIT;
